USE [master]
GO

/****** Object:  Database [procedureDB]    Script Date: 12/28/2016 20:53:32 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'procedureDB')
DROP DATABASE [procedureDB]
GO

USE [master]
GO

/****** Object:  Database [procedureDB]    Script Date: 12/28/2016 20:53:32 ******/
CREATE DATABASE [procedureDB] ON  PRIMARY 
( NAME = N'procedureDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\procedureDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'procedureDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\procedureDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [procedureDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [procedureDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [procedureDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [procedureDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [procedureDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [procedureDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [procedureDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [procedureDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [procedureDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [procedureDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [procedureDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [procedureDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [procedureDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [procedureDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [procedureDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [procedureDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [procedureDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [procedureDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [procedureDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [procedureDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [procedureDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [procedureDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [procedureDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [procedureDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [procedureDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [procedureDB] SET  READ_WRITE 
GO

ALTER DATABASE [procedureDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [procedureDB] SET  MULTI_USER 
GO

ALTER DATABASE [procedureDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [procedureDB] SET DB_CHAINING OFF 
GO


